"""The schema Alembic builds: it matches the models, and the rules the legacy web relied on are
database constraints, not conventions."""

from collections.abc import AsyncIterator

import pytest
from alembic import command
from sqlalchemy import insert, select, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncConnection, create_async_engine

from app.modules.audit.models import ChangeLogRow
from app.modules.auth.models import ShiftRow, UserRow
from app.modules.captures.models import CaptureRow
from app.modules.catalog.models import ProductPriceRow
from app.modules.engine_config.models import ConfigOverrideRow
from app.modules.orders.models import OrderItemRow, OrderRow
from app.modules.pos_settings.models import SettingRow
from tests.api.conftest import alembic_config

TABLES = "change_log, captures, order_items, orders, shifts, users, product_prices, settings, config_overrides"


def test_models_match_the_migrations(migrated_database_url: str) -> None:
    # AutogenerateDiffsDetected if a model changed without a revision (`make migration MSG="..."`)
    command.check(alembic_config(migrated_database_url))


@pytest.fixture
async def conn(migrated_database_url: str) -> AsyncIterator[AsyncConnection]:
    """A connection on the migrated test database, every table emptied first."""
    engine = create_async_engine(migrated_database_url)
    async with engine.begin() as setup:
        await setup.execute(text(f"TRUNCATE {TABLES} RESTART IDENTITY CASCADE"))
    async with engine.connect() as connection:
        yield connection
    await engine.dispose()


async def _user(conn: AsyncConnection, username: str = "staff", **values: object) -> int:
    row = {"username": username, "password_hash": "x", **values}
    return (await conn.execute(insert(UserRow).values(**row).returning(UserRow.id))).scalar_one()


async def test_user_defaults_and_role_check(conn: AsyncConnection) -> None:
    uid = await _user(conn)
    user = (await conn.execute(select(UserRow).where(UserRow.id == uid))).mappings().one()
    assert (user["role"], user["is_active"], user["has_seen_onboarding"], user["full_name"]) == (
        "staff",
        True,
        False,
        "",
    )
    assert user["created_at"].tzinfo is not None
    await conn.commit()
    with pytest.raises(IntegrityError, match="ck_users_role"):
        await _user(conn, "boss", role="owner")
    await conn.rollback()
    with pytest.raises(IntegrityError, match="uq_users_username"):
        await _user(conn, "staff")


async def test_an_account_has_at_most_one_open_shift(conn: AsyncConnection) -> None:
    uid, other = await _user(conn), await _user(conn, "admin", role="admin")
    first = (await conn.execute(insert(ShiftRow).values(user_id=uid).returning(ShiftRow.id))).scalar_one()
    await conn.execute(insert(ShiftRow).values(user_id=other))  # another account: fine
    await conn.commit()
    with pytest.raises(IntegrityError, match="ux_shifts_user_id_open"):
        await conn.execute(insert(ShiftRow).values(user_id=uid))
    await conn.rollback()
    # closing the first shift frees the slot
    await conn.execute(text("UPDATE shifts SET ended_at = now() WHERE id = :id"), {"id": first})
    await conn.execute(insert(ShiftRow).values(user_id=uid))
    await conn.commit()
    assert (await conn.execute(text("SELECT count(*) FROM shifts WHERE user_id = :u"), {"u": uid})).scalar_one() == 2


async def test_order_lines_go_with_their_order_and_quantity_is_positive(conn: AsyncConnection) -> None:
    uid = await _user(conn)
    oid = (await conn.execute(insert(OrderRow).values(cashier_id=uid).returning(OrderRow.id))).scalar_one()
    await conn.execute(
        insert(OrderItemRow).values(order_id=oid, product_id="7", unit_price=25_000, evidence={"ocr": {"text": "ABA"}})
    )
    await conn.commit()
    item = (await conn.execute(select(OrderItemRow))).mappings().one()
    assert (item["quantity"], item["flagged"], item["evidence"]) == (1, False, {"ocr": {"text": "ABA"}})
    assert (await conn.execute(select(OrderRow.status))).scalar_one() == "open"

    with pytest.raises(IntegrityError, match="ck_order_items_quantity_positive"):
        await conn.execute(insert(OrderItemRow).values(order_id=oid, product_id="7", quantity=0))
    await conn.rollback()
    with pytest.raises(IntegrityError, match="ck_orders_status"):
        await conn.execute(text("UPDATE orders SET status = 'refunded'"))
    await conn.rollback()

    await conn.execute(text("DELETE FROM orders WHERE id = :id"), {"id": oid})
    await conn.commit()
    assert (await conn.execute(text("SELECT count(*) FROM order_items"))).scalar_one() == 0


async def test_capture_job_state_and_detections(conn: AsyncConnection) -> None:
    uid = await _user(conn)
    oid = (await conn.execute(insert(OrderRow).values(cashier_id=uid).returning(OrderRow.id))).scalar_one()
    boxes = [{"bbox": [1, 2, 30, 40], "item_id": 5, "status": "accepted"}]
    cid = (
        await conn.execute(insert(CaptureRow).values(order_id=oid, detections=boxes).returning(CaptureRow.id))
    ).scalar_one()
    await conn.commit()
    capture = (await conn.execute(select(CaptureRow).where(CaptureRow.id == cid))).mappings().one()
    assert (capture["job_status"], capture["job_error"], capture["detections"]) == ("queued", None, boxes)
    with pytest.raises(IntegrityError, match="ck_captures_job_status"):
        await conn.execute(text("UPDATE captures SET job_status = 'timeout'"))


async def test_money_is_bigint_and_json_values_round_trip(conn: AsyncConnection) -> None:
    # above the 32-bit limit: a day's takings in VND can be
    await conn.execute(insert(ProductPriceRow).values(product_id="7", price=3_000_000_000))
    await conn.execute(
        insert(SettingRow).values(
            [{"key": "similarity_threshold", "value": 0.7}, {"key": "tilt_block_capture", "value": True}]
        )
    )
    await conn.execute(insert(ConfigOverrideRow).values(key="retrieval.top_k", value=6, updated_by="admin"))
    await conn.commit()
    assert (await conn.execute(select(ProductPriceRow.price))).scalar_one() == 3_000_000_000
    settings = dict((await conn.execute(select(SettingRow.key, SettingRow.value))).all())
    assert settings == {"similarity_threshold": 0.7, "tilt_block_capture": True}
    assert (await conn.execute(select(ConfigOverrideRow.value))).scalar_one() == 6
    with pytest.raises(IntegrityError, match="ck_product_prices_price_not_negative"):
        await conn.execute(insert(ProductPriceRow).values(product_id="8", price=-1))


async def test_change_log_keeps_the_row_when_the_account_is_deleted(conn: AsyncConnection) -> None:
    uid = await _user(conn, "admin", role="admin")
    await conn.execute(
        insert(ChangeLogRow).values(
            table_name="product_prices",
            record_id="7",
            field_name="price",
            old_value=None,
            new_value="15500",
            changed_by=uid,
        )
    )
    await conn.execute(text("DELETE FROM users WHERE id = :id"), {"id": uid})
    await conn.commit()
    row = (await conn.execute(select(ChangeLogRow))).mappings().one()
    assert (row["changed_by"], row["new_value"], row["old_value"]) == (None, "15500", None)
